Repository chesskit-app/chesskit-swift, pull requests merged in 2024-05, with the labels that each got.

#24 Fix move tree previous index calculation
  CHANGELOG.md
  Sources/ChessKit/MoveTree.swift
  Tests/ChessKitTests/GameTests.swift
Labels: bug

#25 Release version 0.7.1
  CHANGELOG.md
Labels: release

#26 Added U-FE0E variant selector and implemented logic for draw by insufficient material condition
  Sources/ChessKit/Bitboards/Bitboard.swift
  Sources/ChessKit/Board.swift
  Sources/ChessKit/Piece.swift
  Sources/ChessKit/Position.swift
  Tests/ChessKitTests/BoardTests.swift
Labels: enhancement
