Repository chesskit-app/chesskit-swift, pull requests merged in 2024-08, with the labels that each got.

#37 Implemented Threefold repetition check
  Sources/ChessKit/Bitboards/PieceSet.swift
  Sources/ChessKit/Board.swift
  Sources/ChessKit/Position.swift
  Sources/ChessKit/Special Moves/Castling.swift
  Sources/ChessKit/Special Moves/EnPassant.swift
  Sources/ChessKit/Square.swift
  Tests/ChessKitTests/BoardTests.swift
  Tests/ChessKitTests/SpecialMoveTests.swift
Labels: new feature

#39 Improve board and parsing tests
  CHANGELOG.md
  Sources/ChessKit/Bitboards/Bitboard.swift
  Sources/ChessKit/Bitboards/PieceSet.swift
  Sources/ChessKit/Board.swift
  Sources/ChessKit/Clock.swift
  Sources/ChessKit/Game.swift
  Sources/ChessKit/Parsers/EngineLANParser+Regex.swift
  Sources/ChessKit/Parsers/EngineLANParser.swift
  Sources/ChessKit/Parsers/FENParser.swift
  Sources/ChessKit/Parsers/PGNParser+Regex.swift
  Sources/ChessKit/Parsers/PGNParser.swift
  Sources/ChessKit/Parsers/SANParser+Regex.swift
  Sources/ChessKit/Parsers/SANParser.swift
  Sources/ChessKit/Piece.swift
  Sources/ChessKit/Special Moves/EnPassant.swift
  Tests/ChessKitTests/BoardTests.swift
  Tests/ChessKitTests/CastlingTests.swift
  Tests/ChessKitTests/GameTests.swift
  Tests/ChessKitTests/MoveTests.swift
  Tests/ChessKitTests/MoveTreeTests.swift
  Tests/ChessKitTests/Parsers/EngineLANParserTests.swift
  Tests/ChessKitTests/Parsers/FENParserTests.swift
  Tests/ChessKitTests/Parsers/PGNParserTests.swift
  Tests/ChessKitTests/Parsers/SANParserTests.swift
  Tests/ChessKitTests/Performance/BoardPerformanceTests.swift
  Tests/ChessKitTests/Performance/PGNParserPerformanceTests.swift
  Tests/ChessKitTests/PieceTests.swift
  Tests/ChessKitTests/SpecialMoveTests.swift
  Tests/ChessKitTests/SquareTests.swift
  Tests/ChessKitTests/Utilities/MockBoardDelegate.swift
  Tests/ChessKitTests/Utilities/SampleGames.swift
  Tests/ChessKitTests/Utilities/SamplePositions.swift
Labels: tech

#40 Release version 0.11.0
  CHANGELOG.md
  README.md
Labels: release

#41 Release version 0.12.0
  CHANGELOG.md
  README.md
Labels: release
