Repository chesskit-app/chesskit-swift, pull requests merged in 2025-06, with the labels that each got.

#60 Fix multiple `BoardDelegate.didPromote()` calls
  CHANGELOG.md
  Package.swift
  Sources/ChessKit/Bitboards/Attacks.swift
  Sources/ChessKit/Board.swift
  Sources/ChessKit/Game.swift
  Sources/ChessKit/Move.swift
  Sources/ChessKit/Parsers/PGNParser.swift
  Sources/ChessKit/Parsers/SANParser.swift
  Sources/ChessKit/Piece.swift
  Sources/ChessKit/Position.swift
  Tests/ChessKitTests/BoardTests.swift
  Tests/ChessKitTests/GameTests.swift
  Tests/ChessKitTests/MoveTreeTests.swift
  Tests/ChessKitTests/Parsers/PGNParserTests.swift
  Tests/ChessKitTests/Utilities/MockBoardDelegate.swift
Labels: bug

#61 Migrate unit tests to Swift Testing
  CHANGELOG.md
  Sources/ChessKit/Piece.swift
  Tests/ChessKitTests/BoardTests.swift
  Tests/ChessKitTests/CastlingTests.swift
  Tests/ChessKitTests/GameTests.swift
  Tests/ChessKitTests/MoveTests.swift
  Tests/ChessKitTests/MoveTreeTests.swift
  Tests/ChessKitTests/Parsers/EngineLANParserTests.swift
  Tests/ChessKitTests/Parsers/FENParserTests.swift
  Tests/ChessKitTests/Parsers/PGNParserTests.swift
  Tests/ChessKitTests/Parsers/SANParserTests.swift
  Tests/ChessKitTests/Performance/PGNParserPerformanceTests.swift
  Tests/ChessKitTests/PieceTests.swift
  Tests/ChessKitTests/SpecialMoveTests.swift
  Tests/ChessKitTests/SquareTests.swift
Labels: tech

#62 Release version 0.14.0
  CHANGELOG.md
Labels: release

#63 Fix en passant parsing in SANParser
  CHANGELOG.md
  Sources/ChessKit/Parsers/SANParser.swift
  Sources/ChessKit/Position.swift
  Tests/ChessKitTests/BoardTests.swift
  Tests/ChessKitTests/Parsers/SANParserTests.swift
  Tests/ChessKitTests/PositionTests.swift
Labels: bug

#67 Release version 0.15.0
  CHANGELOG.md
Labels: release

#68 Parsers bug fixes
  Sources/ChessKit/Parsers/PGNParser/PGNParser+MoveText.swift
  Sources/ChessKit/Parsers/SANParser+Regex.swift
  Tests/ChessKitTests/Parsers/PGNParserTests.swift
  Tests/ChessKitTests/Parsers/SANParserTests.swift
  Tests/ChessKitTests/Utilities/SampleGames.swift
Labels: bug
